// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrUGvUxNNj72vKBBurdNkVAhi25ic-Rsk',
    appId: '1:846725259249:web:ff5bcd9b9ce35b2a0eee50',
    messagingSenderId: '846725259249',
    projectId: 'edumake-dede7',
    authDomain: 'edumake-dede7.firebaseapp.com',
    storageBucket: 'edumake-dede7.firebasestorage.app',
    measurementId: 'G-526QJYBZJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGypCP2FlPQW6YPXLm-rXEjmu5TFfyd38',
    appId: '1:846725259249:android:724114b0e18632250eee50',
    messagingSenderId: '846725259249',
    projectId: 'edumake-dede7',
    storageBucket: 'edumake-dede7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAohTAwSaZ3rk32aylTLG1ex1ffdsBSKGA',
    appId: '1:846725259249:ios:6e5545bda19a435e0eee50',
    messagingSenderId: '846725259249',
    projectId: 'edumake-dede7',
    storageBucket: 'edumake-dede7.firebasestorage.app',
    iosClientId:
        '846725259249-p4p15eii8e24h09cip2u2qatt9m3817b.apps.googleusercontent.com',
    iosBundleId: 'com.example.edumakeFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAohTAwSaZ3rk32aylTLG1ex1ffdsBSKGA',
    appId: '1:846725259249:ios:6e5545bda19a435e0eee50',
    messagingSenderId: '846725259249',
    projectId: 'edumake-dede7',
    storageBucket: 'edumake-dede7.firebasestorage.app',
    iosClientId:
        '846725259249-p4p15eii8e24h09cip2u2qatt9m3817b.apps.googleusercontent.com',
    iosBundleId: 'com.example.edumakeFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrUGvUxNNj72vKBBurdNkVAhi25ic-Rsk',
    appId: '1:846725259249:web:bbca26aa812747ce0eee50',
    messagingSenderId: '846725259249',
    projectId: 'edumake-dede7',
    authDomain: 'edumake-dede7.firebaseapp.com',
    storageBucket: 'edumake-dede7.firebasestorage.app',
    measurementId: 'G-L0JH1SLJRF',
  );
}
